***JUAN CAMILO SERRANO CORREA***

***RAFAEL FERNANDO LEAL RAMIREZ***

In [ ]:
#Sistema
import sys 
import os
#Data Sciencie
import pandas as pd
#numerico
import numpy as np
#graficas
import matplotlib.pyplot as plt
import seaborn as sns # estilos de plt
#ML
import tensorflow as tf
import keras 
from keras.models import Sequential, model_from_json
from keras.layers.core import Dense
import sklearn 
from sklearn.model_selection import train_test_split

In [ ]:
#El dataset de las 25 letras del alfabeto, mas las 4 de error, en orden de 34 bits  (Ver hoja de exel)
training_data = np.array([[1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1],[1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1],
                          [1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1],[1,1,1,1,0 ,1,0,0,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,1,1 ,1,1,1,1,0],
                          [1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1],[1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0],
                          [1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1],[1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1],
                          [1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0],[1,1,1,1,1 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0 ,1,1,1,0,0],
                          [1,0,0,0,1 ,1,0,0,1,0 ,1,0,1,0,0 ,1,1,0,0,0 ,1,0,1,0,0 ,1,0,0,1,0 ,1,0,0,0,1],[1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1],
                          [1,0,0,0,1 ,1,1,0,1,1 ,1,1,1,1,1 ,1,0,1,0,1 ,1,0,1,0,1 ,1,0,0,0,1 ,1,0,0,0,1],[1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1],
                          [1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1],[1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,0,0,0,0],
                          [1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1 ,0,0,0,0,1 ,0,0,0,0,1 ,0,0,0,0,1],[1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1 ,1,1,1,0,0 ,1,0,1,1,0 ,1,0,0,1,1],
                          [1,1,1,1,1 ,1,0,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1 ,0,0,0,0,1 ,0,0,0,0,1 ,1,1,1,1,1],[1,1,1,1,1 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0],
                          [1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1],[1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,0,1,1 ,0,1,0,1,0 ,0,1,1,1,0 ,0,0,1,0,0],
                          [1,0,1,0,1 ,1,0,1,0,1 ,1,0,1,0,1 ,1,1,1,1,1 ,1,1,1,1,1 ,0,1,0,1,0 ,0,1,0,1,0],[1,0,0,0,1 ,1,1,0,1,1 ,0,1,1,1,0 ,0,0,1,0,0 ,0,1,1,1,0 ,1,1,0,1,1 ,1,0,0,0,1],
                          [1,0,0,0,1 ,1,1,0,1,1 ,0,1,1,1,0 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0 ,0,0,1,0,0],[1,1,1,1,1 ,0,0,0,0,1 ,0,0,0,1,1 ,0,1,1,1,0 ,1,1,0,0,0 ,1,0,0,0,0 ,1,1,1,1,1],
                          [0,0,1,0,0 ,1,0,0,0,1 ,1,1,0,1,1 ,1,1,0,1,1 ,1,0,1,0,1 ,1,0,1,0,1 ,1,0,1,0,1],[1,1,1,1,1 ,0,0,0,1,0 ,1,0,0,1,0 ,1,0,0,1,0 ,0,0,0,1,0 ,0,0,0,1,0 ,1,1,1,1,0],
                          [0,0,0,1,1 ,0,0,0,1,1 ,0,0,0,1,1 ,0,0,0,1,1 ,0,0,0,1,1 ,0,0,0,1,1 ,0,0,0,1,1],[1,1,0,1,1 ,0,1,0,1,0 ,0,1,0,0,0 ,0,0,1,0,1 ,1,1,1,0,0 ,0,0,0,1,0 ,1,0,1,0,0]],
                         "float32")
#respuesta esperada para cada letra, donde A=0 y B=1 ... Z= 29
target_data_letters = np.array([[0,0,0,0,0],[0,0,0,0,1],[0,0,0,1,0],[0,0,0,1,1],[0,0,1,0,0],[0,0,1,0,1],[0,0,1,1,0],[0,0,1,1,1],
                        [0,1,0,0,0],[0,1,0,0,1],[0,1,0,1,0],[0,1,0,1,1],[0,1,1,0,0],[0,1,1,0,1],[0,1,1,1,0],[0,1,1,1,1],
                        [1,0,0,0,0],[1,0,0,0,1],[1,0,0,1,0],[1,0,0,1,1],[1,0,1,0,0],[1,0,1,0,1],[1,0,1,1,0],[1,0,1,1,1],
                        [1,1,0,0,0],[1,1,0,0,1],[1,1,0,1,0],[1,1,0,1,1],[1,1,1,0,0],[1,1,1,0,1]],"float32")
#Respuesta esperada si la letra es vocal o no, donde [AEIOU=1 others=0, Error=1 Correcto=0]
target_data_vowels = np.array([[1,0],[0,0],[0,0],[0,0],[1,0],[0,0],[0,0],[0,0],[1,0],[0,0],[0,0],[0,0],[0,0],[0,0],[1,0],[0,0],[0,0],[0,0],[0,0],[0,0],[1,0],[0,0],[0,0],[0,0],[0,0],[0,0],[0,1],[0,1],[0,1],[0,1]],"float32")

In [ ]:
#Arquitectura de la ANN (Artificial Neural Network)
model = Sequential()
model.add(Dense(350, input_dim=35, activation='relu'))#primera capa units=16, input=2, activation = relu
model.add(Dense(1000,  activation='tanh'))#Capa de reconocimiento de letra
model.add(Dense(5,  activation='sigmoid'))#Capa de salida  5=numero de target  ,sigmoid

In [ ]:
model2 = Sequential()
model2.add(Dense(250, input_dim=5, activation='relu'))
model2.add(Dense(700,  activation='tanh'))
model2.add(Dense(2,  activation='sigmoid'))

In [ ]:
#Hiperparámetros para el entrenamiento
model.compile(optimizer="adam", loss="mean_squared_error")#categorical_crossentropy
model2.compile(optimizer="adam", loss="mean_squared_error")#categorical_crossentropy

In [ ]:
#dataset_train, dataset_validation = train_test_split(training_data, train_size=0.6,shuffle=True)

#Entrenamiento de la ANN
model.fit(training_data, target_data_letters, epochs=20)
model2.fit(target_data_letters,target_data_vowels, epochs=20)

In [ ]:
#Validacion del modelo
#Aqui deberia probarse con los datos de validation
#Pero como nuestro ejemplo es solo un XOR, no hicimos el splitting
#por lo tanto usamos los mismos datos de entranamiento

testing = model.evaluate(training_data,target_data_letters) #Aqui probamos las letras
testing = model2.evaluate(target_data_letters,target_data_vowels) #Aqui probamos las letras

1/1 [==============================] - 0s 84ms/step - loss: 0.0847


In [ ]:
#Hacer predicciones (inferencia)
#Vamos a mirar que nos responde al ANN ante un nuevo caso

inference = model.predict(training_data)
inference2 = model2.predict(target_data_letters)

#inference = model.predict([[1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,1,1,1,1 ,1,0,0,0,1 ,1,0,0,0,1 ,1,0,0,0,1]])
print("CAPA 1 LETTERS PREDICTIONS \n",inference)
print("\nCAPA 2 VOWELS AND ERROS PREDICTIONS \n",inference2)

CAPA 1 LETTERS PREDICTIONS 
 [[0.05167735 0.31895688 0.33015376 0.22587097 0.6139445 ]
 [0.2563784  0.08176804 0.34568816 0.4154173  0.45832738]
 [0.03033525 0.438038   0.19520342 0.77694774 0.22427136]
 [0.12643993 0.3023857  0.16992074 0.8892325  0.8886124 ]
 [0.06036958 0.06365332 0.83841825 0.32476035 0.2523995 ]
 [0.011215   0.2884643  0.9195992  0.16434324 0.73704726]
 [0.14007297 0.02598712 0.7357278  0.7254135  0.09896523]
 [0.1247423  0.16038716 0.7945881  0.40898398 0.6464284 ]
 [0.0082269  0.90980774 0.2161476  0.3281539  0.4606858 ]
 [0.15310937 0.6711127  0.00924885 0.42922613 0.92332   ]
 [0.03973779 0.82873416 0.05757979 0.90082186 0.09515068]
 [0.05996829 0.7214117  0.09852207 0.76993036 0.45518926]
 [0.1138086  0.91912055 0.92407376 0.16627064 0.08162302]
 [0.02701291 0.808951   0.7813281  0.1617443  0.65146565]
 [0.15468505 0.43066004 0.73663306 0.5064783  0.3759032 ]
 [0.02215865 0.6090029  0.6991633  0.0955812  0.9416028 ]
 [0.90515244 0.07545927 0.07267061 0.244238